openapi: 3.0.3
info:
  title: Sample API
  description: サンプルAPIのOpenAPI仕様書
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8081
    description: ローカル開発環境

paths:
  /api/health:
    get:
      summary: ヘルスチェック
      description: APIの稼働状況を確認します
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: 正常に動作しています
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-01-01T00:00:00Z"

  /api/products:
    get:
      summary: 商品一覧取得
      description: 商品の一覧を取得します
      operationId: getProducts
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: ページ番号
          required: false
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: 1ページあたりの件数
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  total:
                    type: integer
                    example: 100
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: 商品作成
      description: 新しい商品を作成します
      operationId: createProduct
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/products/{id}:
    get:
      summary: 商品詳細取得
      description: 指定されたIDの商品情報を取得します
      operationId: getProductById
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: 商品ID
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: 商品更新
      description: 指定されたIDの商品情報を更新します
      operationId: updateProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: 商品ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: 商品削除
      description: 指定されたIDの商品を削除します
      operationId: deleteProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: 商品ID
          schema:
            type: integer
      responses:
        '204':
          description: 削除成功
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: integer
          description: 商品ID
          example: 1
        name:
          type: string
          description: 商品名
          example: "サンプル商品"
        description:
          type: string
          description: 商品説明
          example: "これはサンプル商品です"
        price:
          type: number
          format: double
          description: 価格
          example: 1000.00
        category:
          type: string
          description: カテゴリ
          example: "電子機器"
        createdAt:
          type: string
          format: date-time
          description: 作成日時
          example: "2024-01-01T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: 更新日時
          example: "2024-01-01T00:00:00Z"

    ProductRequest:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          description: 商品名
          example: "サンプル商品"
        description:
          type: string
          description: 商品説明
          example: "これはサンプル商品です"
        price:
          type: number
          format: double
          description: 価格
          example: 1000.00
        category:
          type: string
          description: カテゴリ
          example: "電子機器"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: エラーコード
          example: "ERROR_CODE"
        message:
          type: string
          description: エラーメッセージ
          example: "エラーが発生しました"
        details:
          type: string
          description: エラー詳細
          example: "詳細なエラー情報"

  responses:
    BadRequest:
      description: リクエストが不正です
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "BAD_REQUEST"
            message: "リクエストパラメータが不正です"

    NotFound:
      description: リソースが見つかりません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "NOT_FOUND"
            message: "指定されたリソースが見つかりません"

    InternalServerError:
      description: サーバー内部エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "INTERNAL_SERVER_ERROR"
            message: "サーバー内部でエラーが発生しました"

